### ISSUE TITLE
Support zeit / now.sh

### ISSUE THREAD

**Issue by antony** [astrocorp42/rocket#7]
I notice support for netlify exists, I assume zeit support could be quite similar to that. Their CLI / API has all the functionality that would be required.

**Comment by antony** [comment]
I'm not sure, I'm refering specifically to now.

I also think there is value in supporting their aliasing somehow, so for instance:

myproject/feature/some-feature

would auto-deploy to `myproject-some-feature.now.sh` - I don't know if you have something like this planned already.

**Comment by z0mbie42** [comment]
a first version has been implemented in 57af99b6eef06e87702f94f3be31ef8079c657da (v1.4.0)

Could you explain more in details the alias thing, I'm not sure to understand.

If I have a directory `myproject/feature/some-feature`

it will auto deploy to `myproject-some-feature.now.sh` ?

**Comment by antony** [comment]
Awesome! The alias thing should be an option yeah. A lot of people use now
for allowing the QA of individual features by auto deployment of PRs.

The idea being that as a PR is opened, it is built by CI and the ticket
updated with the URL where it has been deployed.

For us this was an important part of our CD process.

**Comment by z0mbie42** [comment]
The auto update of PR is not yet planned, if you have any idea on how to implement this in a clean way please open a new Issue.

As I understand the closest way to achieve what you are saying is by using the `name` field: here is an example with `name` set as `"my-app3"` as of v1.4.1

![screenshot_2018-09-06_17-24-45](https://user-images.githubusercontent.com/6172808/45167687-f29abb80-b1f9-11e8-8c2a-bf165b1746cf.png)

I'm closing because `now` is supported, please feel free to open a new issue for a specific feature
